server:
  http:
    port: 3000
  https:
    port: 3001
  ssl:
    privkeyPath: /home/segeg/deploy/ssl/privkey.pem
    pubPath: /home/segeg/deploy/ssl/cert.pem

mongo:
  uri: mongodb://192.168.0.24:28001/date
  user: admin
  password: admin123

jwt:
  secret: HAHA
  expiresIn: 2h

graphql: 
  playground: true
  schemaFile: schema.gql

redis: 
  host: 192.168.0.24
  port: 6401