mongo:
  uri: mongodb://192.168.0.24:28001/date
  user: admin
  password: admin123
  haha: dkfajdks

jwt:
  secret: HAHA
  expiresIn: 

graphql: 
  playground: true
  schemaFile: schema.gql

redis: 
  host: 192.168.0.24
  port: 6401