server:
  http:
    port: 3000
  https:
    port: 3001
  ssl:
    privkeyPath: ../ssl/privkey.pem
    pubPath: ../ssl/cert.pem

mongo:
  uri: mongodb://192.168.0.24:28001/date
  user: admin
  password: admin123

jwt:
  secret: HAHA
  # 60 * 60 * 24 * 30 = 30일치
  expiredSecond: 2592000

graphql: 
  playground: true
  schemaFile: schema.gql

redis: 
  host: 192.168.0.24
  port: 6401

oracle:
  objectStorage:
    configFilePath: ~/.oci/config
    baseUrl: https://objectstorage.ap-seoul-1.oraclecloud.com
    namespace: cnmz3th5qata
    bucketName: couple-bucket